version: '3'

services:


  mysql:
    image: mysql
    container_name: ${MYSQL_HOSTNAME}
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    networks:
      - app-network
#Networks
networks:
  app-network:
